/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class painel_GUI extends javax.swing.JFrame {

    /**
     * Creates new form painel_GUI
     */
    public painel_GUI() {
        initComponents();
        resultado_txt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        multiplicar_btn = new javax.swing.JButton();
        resultado_txt = new javax.swing.JTextField();
        valor1_txt = new javax.swing.JTextField();
        dividir_btn = new javax.swing.JButton();
        subtrair_btn = new javax.swing.JButton();
        somar_btn = new javax.swing.JButton();
        valor2_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        limpar_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 270, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor 1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 20, 70, 14);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resultado");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(220, 30, 100, 30);

        multiplicar_btn.setBackground(new java.awt.Color(153, 153, 153));
        multiplicar_btn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        multiplicar_btn.setForeground(new java.awt.Color(255, 255, 255));
        multiplicar_btn.setText("X");
        multiplicar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(multiplicar_btn);
        multiplicar_btn.setBounds(20, 200, 73, 30);

        resultado_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado_txtActionPerformed(evt);
            }
        });
        jPanel2.add(resultado_txt);
        resultado_txt.setBounds(220, 60, 100, 30);

        valor1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1_txtActionPerformed(evt);
            }
        });
        jPanel2.add(valor1_txt);
        valor1_txt.setBounds(100, 10, 100, 40);

        dividir_btn.setBackground(new java.awt.Color(153, 153, 153));
        dividir_btn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        dividir_btn.setForeground(new java.awt.Color(255, 255, 255));
        dividir_btn.setText("/");
        dividir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividir_btnActionPerformed(evt);
            }
        });
        jPanel2.add(dividir_btn);
        dividir_btn.setBounds(120, 200, 73, 30);

        subtrair_btn.setBackground(new java.awt.Color(153, 153, 153));
        subtrair_btn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        subtrair_btn.setForeground(new java.awt.Color(255, 255, 255));
        subtrair_btn.setText("-");
        subtrair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrair_btnActionPerformed(evt);
            }
        });
        jPanel2.add(subtrair_btn);
        subtrair_btn.setBounds(120, 160, 73, 30);

        somar_btn.setBackground(new java.awt.Color(153, 153, 153));
        somar_btn.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        somar_btn.setForeground(new java.awt.Color(255, 255, 255));
        somar_btn.setText("+");
        somar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(somar_btn);
        somar_btn.setBounds(20, 160, 70, 30);

        valor2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2_txtActionPerformed(evt);
            }
        });
        jPanel2.add(valor2_txt);
        valor2_txt.setBounds(100, 70, 100, 40);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor 2");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 80, 70, 14);

        limpar_btn.setBackground(new java.awt.Color(153, 153, 153));
        limpar_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        limpar_btn.setForeground(new java.awt.Color(255, 255, 255));
        limpar_btn.setText("C");
        limpar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(limpar_btn);
        limpar_btn.setBounds(220, 200, 73, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 50, 340, 240);

        sair_btn.setBackground(new java.awt.Color(255, 51, 51));
        sair_btn.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        sair_btn.setForeground(new java.awt.Color(255, 255, 255));
        sair_btn.setText("X");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(350, 0, 50, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(400, 305));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultado_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado_txtActionPerformed
        
    }//GEN-LAST:event_resultado_txtActionPerformed

    private void valor1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1_txtActionPerformed

    private void subtrair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtrair_btnActionPerformed
          Controller.funcionalidades_DAO.func_subtrair_btn();
    }//GEN-LAST:event_subtrair_btnActionPerformed

    private void somar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somar_btnActionPerformed
        Controller.funcionalidades_DAO.func_somar_btn();
    }//GEN-LAST:event_somar_btnActionPerformed

    private void multiplicar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicar_btnActionPerformed
          Controller.funcionalidades_DAO.func_multiplicar_btn();
    }//GEN-LAST:event_multiplicar_btnActionPerformed

    private void dividir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividir_btnActionPerformed
          Controller.funcionalidades_DAO.func_dividir_btn();
    }//GEN-LAST:event_dividir_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        Controller.funcionalidades_DAO.func_sair_btn();
        
    }//GEN-LAST:event_sair_btnActionPerformed

    private void valor2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2_txtActionPerformed

    private void limpar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_btnActionPerformed
        Controller.funcionalidades_DAO.func_limpar_btn();
    }//GEN-LAST:event_limpar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(painel_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(painel_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(painel_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(painel_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new painel_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dividir_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton limpar_btn;
    private javax.swing.JButton multiplicar_btn;
    public static javax.swing.JTextField resultado_txt;
    private javax.swing.JButton sair_btn;
    private javax.swing.JButton somar_btn;
    private javax.swing.JButton subtrair_btn;
    public static javax.swing.JTextField valor1_txt;
    public static javax.swing.JTextField valor2_txt;
    // End of variables declaration//GEN-END:variables
}
