/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author agdas
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        exit_btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        receita_btn = new javax.swing.JButton();
        declaracao_btn = new javax.swing.JButton();
        atestado_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        senha_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crm_text = new javax.swing.JTextField();
        entrar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        exit_btn1.setBackground(new java.awt.Color(255, 0, 0));
        exit_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit_btn1.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn1.setText("SAIR");
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn1);
        exit_btn1.setBounds(322, 236, 70, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Gerar Relátorio");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 10, 210, 33);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Receita");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 210, 50, 20);

        receita_btn.setBackground(new java.awt.Color(153, 255, 153));
        receita_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        receita_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/receita_icon.png"))); // NOI18N
        receita_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receita_btnActionPerformed(evt);
            }
        });
        jPanel2.add(receita_btn);
        receita_btn.setBounds(290, 120, 113, 90);

        declaracao_btn.setBackground(new java.awt.Color(255, 204, 204));
        declaracao_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        declaracao_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/declaração_icon.png"))); // NOI18N
        declaracao_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declaracao_btnActionPerformed(evt);
            }
        });
        jPanel2.add(declaracao_btn);
        declaracao_btn.setBounds(160, 120, 113, 90);

        atestado_btn.setBackground(new java.awt.Color(255, 255, 153));
        atestado_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        atestado_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/atestado_icon.png"))); // NOI18N
        atestado_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atestado_btnActionPerformed(evt);
            }
        });
        jPanel2.add(atestado_btn);
        atestado_btn.setBounds(20, 120, 113, 90);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Clique no tipo de relátorio desejável:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 80, 260, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Atestado");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 210, 70, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Declaração");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(160, 210, 80, 20);

        jTabbedPane1.addTab("Relátorio", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        exit_btn.setBackground(new java.awt.Color(255, 0, 0));
        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("SAIR");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn);
        exit_btn.setBounds(322, 236, 70, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("TELA DE LOGIN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 210, 33);

        senha_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_textActionPerformed(evt);
            }
        });
        jPanel1.add(senha_text);
        senha_text.setBounds(70, 140, 160, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Digite sua Senha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 120, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Digite seu  CRM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 70, 110, 20);

        crm_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crm_textActionPerformed(evt);
            }
        });
        jPanel1.add(crm_text);
        crm_text.setBounds(70, 90, 160, 20);

        entrar_btn.setBackground(new java.awt.Color(102, 102, 102));
        entrar_btn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        entrar_btn.setForeground(new java.awt.Color(255, 255, 255));
        entrar_btn.setText("ENTRAR");
        entrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(entrar_btn);
        entrar_btn.setBounds(90, 190, 240, 30);

        jTabbedPane1.addTab("Login", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrar_btnActionPerformed

    private void crm_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crm_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crm_textActionPerformed

    private void senha_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_textActionPerformed

    private void receita_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receita_btnActionPerformed
        try {
            Controller.Funcionalidades_DAO.receitaMedica();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_receita_btnActionPerformed

    private void atestado_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atestado_btnActionPerformed
        try {
            Controller.Funcionalidades_DAO.atestadoMedico();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atestado_btnActionPerformed

    private void declaracao_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declaracao_btnActionPerformed
        try {
            Controller.Funcionalidades_DAO.declaracaoCompromisso();
        } catch (Exception ex) {
            Logger.getLogger(Inicio_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_declaracao_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
           Scanner scanner = new Scanner(System.in);
        
        // Exibe uma mensagem simples para o usuário e guarda na variavel
         String resposta = JOptionPane.showInputDialog("Se você deseja realmente encerrar o programa digite <sim>");
        
     
     
        
        // Verifica a resposta
        if ("sim".equalsIgnoreCase(resposta)) {
            JOptionPane.showMessageDialog(null,  " Saindo...");
            System.exit(0);  // Encerra o programa
        } else {
           JOptionPane.showMessageDialog(null, " Então contianuaremos o programa!");
            
        }
        
        scanner.close();  
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
         Scanner scanner = new Scanner(System.in);
        
        // Exibe uma mensagem simples para o usuário e guarda na variavel
         String resposta = JOptionPane.showInputDialog("Se você deseja realmente encerrar o programa digite <sim>");
        
     
     
        
        // Verifica a resposta
        if ("sim".equalsIgnoreCase(resposta)) {
            JOptionPane.showMessageDialog(null,  " Saindo...");
            System.exit(0);  // Encerra o programa
        } else {
           JOptionPane.showMessageDialog(null, " Então contianuaremos o programa!");
            
        }
        
        scanner.close();  
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton atestado_btn;
    private javax.swing.JTextField crm_text;
    public static javax.swing.JButton declaracao_btn;
    private javax.swing.JButton entrar_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JButton receita_btn;
    private javax.swing.JTextField senha_text;
    // End of variables declaration//GEN-END:variables
}
