/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Laboratorio-Info
 */
public class inicial_GUI extends javax.swing.JFrame {

    /**
     * Creates new form inicial_GUI
     */
    public inicial_GUI() {
        initComponents();
        abaixo_img.setVisible(false);
        normal_img.setVisible(false);
        acima_img.setVisible(false);
        obesidade1_img.setVisible(false);
        obesidade2_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Fechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        peso_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idade_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        altura_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        calcular_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resultado_txt = new javax.swing.JTextField();
        abaixo_img = new javax.swing.JLabel();
        normal_img = new javax.swing.JLabel();
        obesidade2_img = new javax.swing.JLabel();
        obesidade1_img = new javax.swing.JLabel();
        acima_img = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Fechar.setBackground(new java.awt.Color(255, 51, 51));
        Fechar.setForeground(new java.awt.Color(255, 255, 255));
        Fechar.setText("X");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        jPanel1.add(Fechar);
        Fechar.setBounds(360, 10, 50, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel3.setText("Calculadora - IMC");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, -10, 230, 70);

        peso_txt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        peso_txt.setText("71");
        peso_txt.setToolTipText("");
        peso_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_txtActionPerformed(evt);
            }
        });
        jPanel2.add(peso_txt);
        peso_txt.setBounds(20, 170, 70, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Resultado:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 240, 60, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("kg/m2.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 260, 50, 14);

        idade_txt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        idade_txt.setText("17");
        idade_txt.setToolTipText("");
        idade_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idade_txtActionPerformed(evt);
            }
        });
        jPanel2.add(idade_txt);
        idade_txt.setBounds(20, 70, 70, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("anos");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 70, 50, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Idade");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 60, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Altura");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 100, 60, 22);

        altura_txt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        altura_txt.setText("1.80");
        altura_txt.setToolTipText("");
        altura_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altura_txtActionPerformed(evt);
            }
        });
        jPanel2.add(altura_txt);
        altura_txt.setBounds(20, 120, 70, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Seu IMC é de ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 250, 100, 17);

        calcular_btn.setBackground(new java.awt.Color(102, 204, 255));
        calcular_btn.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        calcular_btn.setForeground(new java.awt.Color(255, 255, 255));
        calcular_btn.setText("Calcular");
        calcular_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_btnActionPerformed(evt);
            }
        });
        jPanel2.add(calcular_btn);
        calcular_btn.setBounds(30, 200, 150, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Peso");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 150, 60, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("metros");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 120, 50, 17);

        resultado_txt.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jPanel2.add(resultado_txt);
        resultado_txt.setBounds(150, 250, 40, 20);

        abaixo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/abaixo.png"))); // NOI18N
        jPanel2.add(abaixo_img);
        abaixo_img.setBounds(190, 140, 50, 120);

        normal_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/normal.png"))); // NOI18N
        jPanel2.add(normal_img);
        normal_img.setBounds(190, 150, 50, 90);

        obesidade2_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/obesidade2.png"))); // NOI18N
        jPanel2.add(obesidade2_img);
        obesidade2_img.setBounds(190, 150, 50, 100);

        obesidade1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/obesidade1.png"))); // NOI18N
        jPanel2.add(obesidade1_img);
        obesidade1_img.setBounds(190, 150, 50, 90);

        acima_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/acima.png"))); // NOI18N
        jPanel2.add(acima_img);
        acima_img.setBounds(190, 150, 50, 100);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Kg");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 170, 50, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 250, 280);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 7)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("IMC\tClassificação\nMenor que 18,5\tMagreza\n18,5 a 24,9\tNormal\n25 a 29,9\tSobrepeso\n30 a 34,9\tObesidade grau I\n35 a 39,9\tObesidade grau II\nMaior que 40\tObesidade grau III");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 200, 150, 96);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 300);

        setSize(new java.awt.Dimension(419, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FecharActionPerformed

    private void peso_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_txtActionPerformed

    private void idade_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idade_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idade_txtActionPerformed

    private void altura_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altura_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altura_txtActionPerformed

    private void calcular_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_btnActionPerformed
        Controller.Calcula_DAO.func_calcular_imc_btn();
    }//GEN-LAST:event_calcular_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    public static javax.swing.JLabel abaixo_img;
    public static javax.swing.JLabel acima_img;
    public static javax.swing.JTextField altura_txt;
    public static javax.swing.JButton calcular_btn;
    public static javax.swing.JTextField idade_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public static javax.swing.JLabel normal_img;
    public static javax.swing.JLabel obesidade1_img;
    public static javax.swing.JLabel obesidade2_img;
    public static javax.swing.JTextField peso_txt;
    public static javax.swing.JTextField resultado_txt;
    // End of variables declaration//GEN-END:variables
}
